### PR TITLE
Project1 merk1.1

### PR DESCRIPTION
**Pull request by damadi37**

### CODE REVIEW

**Comment by merkman** [comment]
It's somebody print everything out?

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 16, 2016 at 4:42 PM, Dacia C<notifications@github.com> wrote:   
You can view, comment on, or merge this pull request online at:

  https://github.com/damadi37/ICS372_Summer/pull/22

Commit Summary
   
   - Updated Use Case Excel File
   - Merge remote-tracking branch 'refs/remotes/origin/Project1Dacia1.0' into Project1Merk1.1
   - Merge remote-tracking branch 'refs/remotes/origin/master' into Project1Merk1.1
   - Merge remote-tracking branch 'refs/remotes/origin/master' into Project1Merk1.1
   - First Draft of All Use Cases
   - Change
   - Merge remote-tracking branch 'refs/remotes/origin/master' into Project1Merk1.1

File Changes
   
   -  M UseCasesAll.xlsx (0) 

Patch Links:
   
   - https://github.com/damadi37/ICS372_Summer/pull/22.patch
   - https://github.com/damadi37/ICS372_Summer/pull/22.diff

**Comment by damadi37** [comment]
No I didn't

**Comment by merkman** [comment]
We can just use a controller in between the theatre model and the UI. The UI creates a new instance of the controller passing it the load from file parameter. If the load from file parameter is true then it DC realises and passes the loaded object to the UI. If the parameter is no then the controller create a new theater object and passes it to the UI

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 16, 2016 at 5:33 PM, Dacia C<notifications@github.com> wrote:   
Merged #22.

**Comment by damadi37** [comment]
I think it's over complicating it for this class. I think we only need to do what's in the book and I think the controller wouldn't really be the controller since the theatre is doing that job anyway. I think we can just do what the professor is looking for and call it a day. You and I both know that's not how it would actually be done so we can still sleep at night.

**Comment by merkman** [comment]
Sounds good.

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 16, 2016 at 10:22 PM, Dacia C<notifications@github.com> wrote:   I think it's over complicating it for this class. I think we only need to do what's in the book and I think the controller wouldn't really be the controller since the theatre is doing that job anyway. I think we can just do what the professor is looking for and call it a day. You and I both know that's not how it would actually be done so we can still sleep at night.

**Pull request merged**
